name: pikowl
description: Pikowl a drinking game

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^1.2.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  lottie: ^1.3.0
  very_good_analysis: ^2.4.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/json/
    - assets/lottie/
